const catchAsync = require('../utils/catchAsync');
const Product = require('../models/productModel');
const AppError = require('../utils/AppError');
const factory = require('./handlerFactory')
exports.getAll = factory.getAll(Product)
exports.getOne = factory.getOne(Product)
exports.create = factory.create(Product)
exports.update = factory.update(Product)
exports.delete = factory.delete(Product)